name: StaffPlugin
version: '${version}'
main: me.riches.staffplugin.StaffPlugin
api-version: 1.17
authors: [ riches_exe, Zepsun ]
description: Testing Plugin For Riches
commands:
  admin:
    description: Admin panel for admins
    usage: /admin
  smite:
    description: Smite a user
    usage: /smite [user]
  vanish:
    description: Vanish from all players
    usage: /vanish