name: TestingPlugin
version: '${version}'
main: me.riches.testingplugin.TestingPlugin
api-version: 1.17
authors: [ riches_exe, Zepsun ]
description: Testing Plugin For Riches
commands:
  spawn:
    description: Teleport to spawn
    usage: /spawn

  admin:
    description: Admin panel for admins
    usage: /admin

  setspawn:
    description: Set the spawn for the server.
    usage: /setspawn

  smite:
    description: Smite a user
    usage: /smite [user]